'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=.\MSSQLSERVER2008;Initial Catalog=CyberHRM;User ID=sa;Password=tiger")>  _
        Public ReadOnly Property CyberHRM() As String
            Get
                Return CType(Me("CyberHRM"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-UVBOUBQ\SQLEXPRESS;Initial Catalog=dbTraining;Integrated Secu"& _ 
            "rity=True")>  _
        Public ReadOnly Property dbTraining() As String
            Get
                Return CType(Me("dbTraining"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.8.142\sqlserver2017;Initial Catalog=dbTraining2017;User ID=sa"& _ 
            ";Password=tiger")>  _
        Public ReadOnly Property dbTraining2017() As String
            Get
                Return CType(Me("dbTraining2017"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TG11508\TGS_EXPRESS;Initial Catalog=dbTraining;Integrated Security=Tr"& _ 
            "ue")>  _
        Public ReadOnly Property dbTraining1() As String
            Get
                Return CType(Me("dbTraining1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TG11508\TGS_EXPRESS;Initial Catalog=dbTraining;Integrated Security=Tr"& _ 
            "ue")>  _
        Public ReadOnly Property dbTraining2() As String
            Get
                Return CType(Me("dbTraining2"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TG11508\TGS_EXPRESS;Initial Catalog=dbTraining;Integrated Security=Tr"& _ 
            "ue")>  _
        Public ReadOnly Property dbTraining3() As String
            Get
                Return CType(Me("dbTraining3"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TG11512\;Initial Catalog=dbTrainningHRIS;User ID=sa;Password=tiger")>  _
        Public ReadOnly Property dbTrainningHRIS() As String
            Get
                Return CType(Me("dbTrainningHRIS"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TG11512\;Initial Catalog=dbTrainningHRIS;User ID=sa;Password=tiger")>  _
        Public ReadOnly Property dbTrainningHRIS1() As String
            Get
                Return CType(Me("dbTrainningHRIS1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TGDV01\MSSQL2017;Initial Catalog=dbTrainning;User ID=sa;Password=tige"& _ 
            "r")>  _
        Public ReadOnly Property dbTrainning() As String
            Get
                Return CType(Me("dbTrainning"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TGDV01\MSSQL2017;Initial Catalog=dbTrainning;User ID=sa;Password=tige"& _ 
            "r")>  _
        Public ReadOnly Property dbTrainning1() As String
            Get
                Return CType(Me("dbTrainning1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TG11518;Initial Catalog=HRISDB_Man;User ID=sa;Password=tiger")>  _
        Public ReadOnly Property HRISDBMan() As String
            Get
                Return CType(Me("HRISDBMan"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TG11518;Initial Catalog=HRISDB_Man;User ID=sa;Password=tiger")>  _
        Public ReadOnly Property HRISDBMan1() As String
            Get
                Return CType(Me("HRISDBMan1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TGDV01\MSSQL2017;Initial Catalog=dbTrainning;User ID=sa;Password=tige"& _ 
            "r")>  _
        Public ReadOnly Property dbTrainning2() As String
            Get
                Return CType(Me("dbTrainning2"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TGDV01\MSSQL2017;Initial Catalog=dbTrainning;User ID=sa;Password=tige"& _ 
            "r")>  _
        Public ReadOnly Property dbTrainning3() As String
            Get
                Return CType(Me("dbTrainning3"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TG11521\SQLEXPRESS;Initial Catalog=HRISTraining;User ID=sa;Password=t"& _ 
            "iger")>  _
        Public ReadOnly Property HRISTraining() As String
            Get
                Return CType(Me("HRISTraining"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TG11521\SQLEXPRESS;Initial Catalog=testDatabase;User ID=sa;Password=t"& _ 
            "iger")>  _
        Public ReadOnly Property testDatabase() As String
            Get
                Return CType(Me("testDatabase"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TG11521\SQLEXPRESS;Initial Catalog=testDatabase;User ID=sa;Password=t"& _ 
            "iger")>  _
        Public ReadOnly Property testDatabase1() As String
            Get
                Return CType(Me("testDatabase1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TG11521\SQLEXPRESS;Initial Catalog=testDatabase;Persist Security Info"& _ 
            "=True;User ID=sa;Password=tiger")>  _
        Public ReadOnly Property testDatabase2() As String
            Get
                Return CType(Me("testDatabase2"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TG11521\SQLEXPRESS;Initial Catalog=testDatabase;Persist Security Info"& _ 
            "=True;User ID=sa;Password=tiger")>  _
        Public ReadOnly Property testDatabase3() As String
            Get
                Return CType(Me("testDatabase3"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TG11521\SQLEXPRESS;Initial Catalog=testDatabase;Persist Security Info"& _ 
            "=True;User ID=sa;Password=tiger")>  _
        Public ReadOnly Property testDatabase4() As String
            Get
                Return CType(Me("testDatabase4"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TG11521\SQLEXPRESS;Initial Catalog=testDatabase;User ID=sa;Password=t"& _ 
            "iger")>  _
        Public ReadOnly Property testDatabase5() As String
            Get
                Return CType(Me("testDatabase5"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TG11521\SQLEXPRESS;Initial Catalog=testDatabase;User ID=sa;Password=t"& _ 
            "iger")>  _
        Public ReadOnly Property testDatabase6() As String
            Get
                Return CType(Me("testDatabase6"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TG11521\SQLEXPRESS;Initial Catalog=testDatabase;User ID=sa;Password=t"& _ 
            "iger")>  _
        Public ReadOnly Property testDatabase7() As String
            Get
                Return CType(Me("testDatabase7"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TG11521\SQLEXPRESS;Initial Catalog=testDatabase;User ID=sa;Password=t"& _ 
            "iger")>  _
        Public ReadOnly Property testDatabase8() As String
            Get
                Return CType(Me("testDatabase8"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TG11521\SQLEXPRESS;Initial Catalog=testDatabase;User ID=sa;Password=t"& _ 
            "iger")>  _
        Public ReadOnly Property testDatabase9() As String
            Get
                Return CType(Me("testDatabase9"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TG11521\SQLEXPRESS;Initial Catalog=testDatabase;User ID=sa;Password=t"& _ 
            "iger")>  _
        Public ReadOnly Property testDatabase10() As String
            Get
                Return CType(Me("testDatabase10"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TG11521\SQLEXPRESS;Initial Catalog=testDatabase;Integrated Security=T"& _ 
            "rue")>  _
        Public ReadOnly Property testDatabase11() As String
            Get
                Return CType(Me("testDatabase11"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TG11521\SQLEXPRESS;Initial Catalog=testDatabase;Integrated Security=T"& _ 
            "rue")>  _
        Public ReadOnly Property testDatabase12() As String
            Get
                Return CType(Me("testDatabase12"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TG11521\SQLEXPRESS;Initial Catalog=testDatabase;User ID=sa;Password=t"& _ 
            "iger")>  _
        Public ReadOnly Property testDatabase13() As String
            Get
                Return CType(Me("testDatabase13"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TG11521\SQLEXPRESS;Initial Catalog=testDatabase;User ID=sa;Password=t"& _ 
            "iger")>  _
        Public ReadOnly Property testDatabase14() As String
            Get
                Return CType(Me("testDatabase14"),String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TG11511;Initial Catalog=repair;User ID=sa;Password=tiger")>
        Public ReadOnly Property repair() As String
            Get
                Return CType(Me("repair"), String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.CLB_Training.My.MySettings
            Get
                Return Global.CLB_Training.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
